<template>
   <div class="task">

      <div :class="`task__content ${task.done ? 'task__content--done' : ''}`">
            <input :ref="task.id" class="task__input" type="text" placeholder="New task" v-model="task.text">
            <button class="task__done" aria-label="Done" @click="emitDone"><ToDoIcon /></button>
      </div>

      <button class="task__remove" aria-label="Remove" @click="emitRemove">Remove</button>
   </div>
</template>

<script>
   import ToDoIcon from "../components/ToDoIcon.vue"

   export default {
      props: {
         task: { type: Object }
      },

      components: {
         ToDoIcon,
      },

      // Vues native queryselector, the function points on objects through its ID generated by 'id()'.
      mounted() {
         const input = this.$refs[this.task.id];

         input.focus();
      },

      // Sends input update actively to 'tasks' array in the parent-element.
      updated() {
         this.$emit("updated-task", this.task);
      },

      methods: {
         // Sends an event on activation to the 'doneTask' function in the parent-element.
         emitDone() {
            this.$emit("done-task", this.task);
         },

         // Sends an event on activation to the 'removeTask' function in the parent-element.
         emitRemove() {
            this.$emit("remove-task", this.task);
         },
      },
   }
</script>

<style>
   .task {
      display: flex;
      margin: 1% 0% 1% 0%;
   }

   .task__content {
      width: 90%;
      height: 30px;
      background: white;
      border-radius: 15px;
      display: flex;
      justify-content: space-between;
      align-items: center;
   }

   .task__done {
      background: none;
      border: none;
      margin: 0rem 0.5rem 0rem 0.5rem;
   }

   .task__input {
      width: 100%;
      height: 100%;
      color: #032B43;
      font-size: 1.05rem;
      background: none;
      border: none;
      margin-left: 0.5rem;
   }

   .task__remove {
      width: 4.2rem;
      color: #FFBA08;
      background: none;
      border: none;
      cursor: pointer;
      margin-left: 3%;
   }

   .task__remove:hover {
      color: white;
      font-size: 1rem;
      transition: ease-in-out 0.2s;
   }

   .task__content--done circle {
      fill: #FFBA08;
      stroke: #FFBA08;
   }

   .task__content--done circle:hover {
      stroke: #032B43;
   }
</style>